# Generated by Django 3.2.9 on 2022-02-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220210_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='details',
            new_name='despriction',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='details',
            new_name='despriction',
        ),
    ]
